### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by garrickajo** [cyaninc/beaker#60]
I tried to run the `npm install` command, and was getting an error that curl.h was not found. 

After installing libcurl4-gnutls-dev, other errors were happening. Down below is only the error out. Curl version follows.

```
$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

```
npm WARN package.json Dependency 'lodash' exists in both dependencies and devDependencies, using 'lodash@^3.2.0' from dependencies
child_process: customFds option is deprecated, use stdio instead.
../curllib.cc:26:28: error: expected class-name before ‘{’ token
 class CurlLib : ObjectWrap {
                            ^
../curllib.cc:59:34: error: ‘Arguments’ does not name a type
   static Handle<Value> New(const Arguments& args) {
                                  ^
../curllib.cc:59:45: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> New(const Arguments& args) {
                                             ^
../curllib.cc:92:35: error: ‘Arguments’ does not name a type
   static Handle<Value> Body(const Arguments& args) {
                                   ^
../curllib.cc:92:46: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> Body(const Arguments& args) {
                                              ^
../curllib.cc:114:34: error: ‘Arguments’ does not name a type
   static Handle<Value> Run(const Arguments& args) {
                                  ^
../curllib.cc:114:45: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> Run(const Arguments& args) {
                                             ^
../curllib.cc: In static member function ‘static void CurlLib::Init(v8::Handle<v8::Object>)’:
../curllib.cc:38:58: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                          ^
../curllib.cc:38:58: note: candidate is:
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../curllib.cc:40:47: error: no matching function for call to ‘v8::Persistent<v8::FunctionTemplate>::New(v8::Local<v8::FunctionTemplate>&)’
     s_ct = Persistent<FunctionTemplate>::New(t);
                                               ^
../curllib.cc:40:47: note: candidate is:
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::FunctionTemplate]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note:   candidate expects 2 arguments, 1 provided
../curllib.cc:41:9: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
     s_ct->InstanceTemplate()->SetInternalFieldCount(1);
         ^
../curllib.cc:42:9: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
     s_ct->SetClassName(String::NewSymbol("CurlLib"));
         ^
../curllib.cc:42:24: error: ‘NewSymbol’ is not a member of ‘v8::String’
     s_ct->SetClassName(String::NewSymbol("CurlLib"));
                        ^
../curllib.cc:44:47: error: could not convert ‘CurlLib::s_ct’ from ‘v8::Persistent<v8::FunctionTemplate>’ to ‘v8::Handle<v8::FunctionTemplate>’
     NODE_SET_PROTOTYPE_METHOD(s_ct, "run", Run);
                                               ^
../curllib.cc:45:49: error: could not convert ‘CurlLib::s_ct’ from ‘v8::Persistent<v8::FunctionTemplate>’ to ‘v8::Handle<v8::FunctionTemplate>’
     NODE_SET_PROTOTYPE_METHOD(s_ct, "body", Body);
                                                 ^
../curllib.cc:47:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("CurlLib"),
                 ^
../curllib.cc:48:21: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
                 s_ct->GetFunction());
                     ^
../curllib.cc:50:49: error: ‘NODE_PSYMBOL’ was not declared in this scope
     sym_body_length = NODE_PSYMBOL("body_length");
                                                 ^
../curllib.cc: In static member function ‘static v8::Handle<v8::Value> CurlLib::New(const int&)’:
../curllib.cc:61:14: error: ‘class CurlLib’ has no member named ‘Wrap’
     curllib->Wrap(args.This());
              ^
../curllib.cc:61:24: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
     curllib->Wrap(args.This());
                        ^
../curllib.cc:62:17: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
     return args.This();
                 ^
../curllib.cc: In static member function ‘static void CurlLib::copy_to_buffer(buff_t&, v8::Local<v8::String>&)’:
../curllib.cc:88:12: error: ‘class v8::String’ has no member named ‘WriteAscii’
       src->WriteAscii(&dest[0], 0, src->Length());
            ^
../curllib.cc: In static member function ‘static v8::Handle<v8::Value> CurlLib::Body(const int&)’:
../curllib.cc:93:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1 || !Buffer::HasInstance(args[0])) {
              ^
../curllib.cc:93:57: error: invalid types ‘const int[int]’ for array subscript
     if (args.Length() < 1 || !Buffer::HasInstance(args[0])) {
                                                         ^
../curllib.cc:22:39: error: ‘New’ is not a member of ‘v8::String’
   ThrowException(Exception::TypeError(String::New("Bad argument")))
                                       ^
../curllib.cc:94:14: note: in expansion of macro ‘THROW_BAD_ARGS’
       return THROW_BAD_ARGS;
              ^
../curllib.cc:22:67: error: ‘ThrowException’ was not declared in this scope
   ThrowException(Exception::TypeError(String::New("Bad argument")))
                                                                   ^
../curllib.cc:94:14: note: in expansion of macro ‘THROW_BAD_ARGS’
       return THROW_BAD_ARGS;
              ^
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../curllib.cc:97:17: error: within this context
     HandleScope scope;
                 ^
../curllib.cc:98:38: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> buffer_obj = args[0]->ToObject();
                                      ^
../curllib.cc:104:9: error: ‘New’ is not a member of ‘v8::String’
         String::New("Insufficient Buffer Length")));
         ^
../curllib.cc:104:51: error: ‘ThrowException’ was not declared in this scope
         String::New("Insufficient Buffer Length")));
                                                   ^
../curllib.cc:111:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buffer_obj);
                  ^
../curllib.cc: In static member function ‘static v8::Handle<v8::Value> CurlLib::Run(const int&)’:
../curllib.cc:115:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1) {
              ^
../curllib.cc:22:39: error: ‘New’ is not a member of ‘v8::String’
   ThrowException(Exception::TypeError(String::New("Bad argument")))
                                       ^
../curllib.cc:116:14: note: in expansion of macro ‘THROW_BAD_ARGS’
       return THROW_BAD_ARGS;
              ^
../curllib.cc:22:67: error: ‘ThrowException’ was not declared in this scope
   ThrowException(Exception::TypeError(String::New("Bad argument")))
                                                                   ^
../curllib.cc:116:14: note: in expansion of macro ‘THROW_BAD_ARGS’
       return THROW_BAD_ARGS;
              ^
../curllib.cc:119:32: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_method = String::New("method");
                                ^
../curllib.cc:120:29: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_url = String::New("url");
                             ^
../curllib.cc:121:33: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_headers = String::New("headers");
                                 ^
../curllib.cc:122:30: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_body = String::New("body");
                              ^
../curllib.cc:123:44: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_connect_timeout_ms = String::New("connect_timeout_ms");
                                            ^
../curllib.cc:124:36: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_timeout_ms = String::New("timeout_ms");
                                    ^
../curllib.cc:125:44: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_rejectUnauthorized = String::New("rejectUnauthorized");
                                            ^
../curllib.cc:126:32: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_caCert = String::New("ca");
                                ^
../curllib.cc:127:36: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_clientCert = String::New("cert");
                                    ^
../curllib.cc:128:29: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_pfx = String::New("pfx");
                             ^
../curllib.cc:129:35: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_clientKey = String::New("key");
                                   ^
../curllib.cc:130:41: error: ‘New’ is not a member of ‘v8::String’
     Local<String> key_clientKeyPhrase = String::New("passphrase");
                                         ^
../curllib.cc:132:44: error: ‘New’ is not a member of ‘v8::String’
     static const Local<String> PFXFORMAT = String::New("P12");
                                            ^
../curllib.cc:134:49: error: invalid types ‘const int[int]’ for array subscript
     Local<Array> opt = Local<Array>::Cast(args[0]);
                                                 ^
../curllib.cc:22:39: error: ‘New’ is not a member of ‘v8::String’
   ThrowException(Exception::TypeError(String::New("Bad argument")))
                                       ^
../curllib.cc:139:14: note: in expansion of macro ‘THROW_BAD_ARGS’
       return THROW_BAD_ARGS;
              ^
../curllib.cc:22:67: error: ‘ThrowException’ was not declared in this scope
   ThrowException(Exception::TypeError(String::New("Bad argument")))
                                                                   ^
../curllib.cc:139:14: note: in expansion of macro ‘THROW_BAD_ARGS’
       return THROW_BAD_ARGS;
              ^
../curllib.cc:22:39: error: ‘New’ is not a member of ‘v8::String’
   ThrowException(Exception::TypeError(String::New("Bad argument")))
                                       ^
../curllib.cc:144:14: note: in expansion of macro ‘THROW_BAD_ARGS’
       return THROW_BAD_ARGS;
              ^
../curllib.cc:22:67: error: ‘ThrowException’ was not declared in this scope
   ThrowException(Exception::TypeError(String::New("Bad argument")))
                                                                   ^
../curllib.cc:144:14: note: in expansion of macro ‘THROW_BAD_ARGS’
       return THROW_BAD_ARGS;
              ^
../curllib.cc:150:28: error: ‘New’ is not a member of ‘v8::String’
     Local<String> body   = String::New((const char*)"", 0);
                            ^
../curllib.cc:151:30: error: ‘New’ is not a member of ‘v8::String’
     Local<String> caCert   = String::New((const char*)"", 0);
                              ^
../curllib.cc:152:34: error: ‘New’ is not a member of ‘v8::String’
     Local<String> clientCert   = String::New((const char*)"", 0);
                                  ^
../curllib.cc:153:40: error: ‘New’ is not a member of ‘v8::String’
     Local<String> clientCertFormat   = String::New((const char*)"", 0);
                                        ^
../curllib.cc:154:33: error: ‘New’ is not a member of ‘v8::String’
     Local<String> clientKey   = String::New((const char*)"", 0);
                                 ^
../curllib.cc:155:39: error: ‘New’ is not a member of ‘v8::String’
     Local<String> clientKeyPhrase   = String::New((const char*)"", 0);
                                       ^
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../curllib.cc:226:17: error: within this context
     HandleScope scope;
                 ^
../curllib.cc:309:40: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> result = Object::New();
                                        ^
../curllib.cc:309:40: note: candidate is:
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../curllib.cc:312:62: error: no matching function for call to ‘v8::Integer::New(std::basic_string<char>::size_type)’
       result->Set(sym_body_length, Integer::New(buffer.size()));
                                                              ^
../curllib.cc:312:62: note: candidate is:
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../curllib.cc:313:36: error: no matching function for call to ‘v8::Array::New()’
       Local<Array> _h = Array::New();
                                    ^
../curllib.cc:313:36: note: candidate is:
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:23: note: static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:23: note:   candidate expects 2 arguments, 0 provided
../curllib.cc:315:20: error: ‘New’ is not a member of ‘v8::String’
         _h->Set(i, String::New(headers[i].c_str()));
                    ^
../curllib.cc:317:34: error: no matching function for call to ‘v8::Object::Set(v8::Persistent<v8::String>&, v8::Local<v8::Array>&)’
       result->Set(sym_headers, _h);
                                  ^
../curllib.cc:317:34: note: candidates are:
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>)
   bool Set(Handle<Value> key, Handle<Value> value);
        ^
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::String>’ to ‘v8::Handle<v8::Value>’
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   bool Set(uint32_t index, Handle<Value> value);
        ^
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::String>’ to ‘uint32_t {aka unsigned int}’
../curllib.cc:320:47: error: no matching function for call to ‘v8::Integer::New(int)’
       result->Set(sym_timedout, Integer::New(1));
                                               ^
../curllib.cc:320:47: note: candidate is:
In file included from ../curllib.cc:8:0:
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../curllib.cc:322:30: error: ‘New’ is not a member of ‘v8::String’
       result->Set(sym_error, String::New(curl_easy_strerror(res)));
                              ^
../curllib.cc:326:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(result);
                  ^
make: *** [Release/obj.target/curllib/curllib.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-52-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gajo/local/node_src/beaker/node_modules/http-sync
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! http-sync@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the http-sync@0.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the http-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls http-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gajo/local/node_src/beaker/npm-debug.log
```

**Comment by job13er** [comment]
Hmm. I haven't seen that one before. I'm working on a new version which should not need `http-sync` and so shouldn't need `lib-curl` anymore. I'll try to get it out in the next couple days. If it looks like I won't be able to, I'll try to dig into what's happening for you. 

What OS are you using?

**Comment by job13er** [comment]
Hmm. I haven't seen that one before. I'm working on a new version which should not need `http-sync` and so shouldn't need `lib-curl` anymore. I'll try to get it out in the next couple days. If it looks like I won't be able to, I'll try to dig into what's happening for you. 

What OS are you using?

**Comment by garrickajo** [comment]
Thanks, Adam. No worries about my specific case. I'm happy to wait for the
new version. I'm using Ubuntu 14.04, Unity.

**Comment by job13er** [comment]
@garrickajo Did you install `libcurl4-openssl-dev` as indicated in the [README](https://github.com/cyaninc/beaker#lib-curl)?

**Comment by garrickajo** [comment]
Yes, sorry I wasn't specific. Then I looked to update it, but I think it was updated already.

```
$ dpkg -l | grep libcurl

ii  libcurl3:amd64                                        7.35.0-1ubuntu2.5                                   amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64                                 7.35.0-1ubuntu2.5                                   amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4-openssl-dev:amd64                            7.35.0-1ubuntu2.5                                   amd64        development files and documentation for libcurl (OpenSSL flavour)
ii  python-pycurl                                         7.19.3-0ubuntu3                                     amd64        Python bindings to libcurl
ii  python3-pycurl                                        7.19.3-0ubuntu3                                     amd64        Python 3 bindings to libcurl
```

**library specifics**

```
$ apt-cache show libcurl4-openssl-dev

Package: libcurl4-openssl-dev
Priority: optional
Section: libdevel
Installed-Size: 1199
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Alessandro Ghedini <ghedo@debian.org>
Architecture: amd64
Source: curl
Version: 7.35.0-1ubuntu2.5
Provides: libcurl-dev, libcurl-ssl-dev, libcurl3-dev, libcurl3-openssl-dev, libcurl4-dev
Depends: libcurl3 (= 7.35.0-1ubuntu2.5), libc6-dev | libc-dev, libidn11-dev, libkrb5-dev, libldap2-dev, librtmp-dev, libssl-dev, zlib1g-dev
Suggests: libcurl4-doc, libcurl3-dbg
Conflicts: libcurl4-gnutls-dev, libcurl4-nss-dev
Filename: pool/main/c/curl/libcurl4-openssl-dev_7.35.0-1ubuntu2.5_amd64.deb
Size: 244762
MD5sum: b1642299a91afca64423352a7d9c5836
SHA1: 281118900779375d060000ba05d50f83c7a2b6fb
SHA256: f63b357cf0557ad48b225c4ea6bcafa7cb83a9d61a924ab5f4c0bb0f6394c7b3
Description-en: development files and documentation for libcurl (OpenSSL flavour)
 libcurl is an easy-to-use client-side URL transfer library, supporting DICT,
 FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, POP3, POP3S,
 RTMP, RTSP, SCP, SFTP, SMTP, SMTPS, TELNET and TFTP.
 .
 libcurl supports SSL certificates, HTTP POST, HTTP PUT, FTP uploading, HTTP
 form based upload, proxies, cookies, user+password authentication (Basic,
 Digest, NTLM, Negotiate, Kerberos), file transfer resume, http proxy tunneling
 and more!
 .
 libcurl is free, thread-safe, IPv6 compatible, feature rich, well supported,
 fast, thoroughly documented and is already used by many known, big and
 successful companies and numerous applications.
 .
 This package provides the development files (ie. includes, static library,
 manual pages) that allow to build software which uses libcurl.
 .
 SSL support is provided by OpenSSL.
Description-md5: 9ef3e0d3a9a6f50f79b0deaff858c410
Multi-Arch: same
Homepage: http://curl.haxx.se
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m

Package: libcurl4-openssl-dev
Priority: optional
Section: libdevel
Installed-Size: 1197
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Alessandro Ghedini <ghedo@debian.org>
Architecture: amd64
Source: curl
Version: 7.35.0-1ubuntu2
Provides: libcurl-dev, libcurl-ssl-dev, libcurl3-dev, libcurl3-openssl-dev, libcurl4-dev
Depends: libcurl3 (= 7.35.0-1ubuntu2), libc6-dev | libc-dev, libidn11-dev, libkrb5-dev, libldap2-dev, librtmp-dev, libssl-dev, zlib1g-dev
Suggests: libcurl4-doc, libcurl3-dbg
Conflicts: libcurl4-gnutls-dev, libcurl4-nss-dev
Filename: pool/main/c/curl/libcurl4-openssl-dev_7.35.0-1ubuntu2_amd64.deb
Size: 243100
MD5sum: 03e9530effce3a09e0595345060fec0f
SHA1: a6f37a0764449e6c7ea29cc6f7baf4a948d71c60
SHA256: f5df5de5464f2cb327a4c4655185357b16afbb7b01d35f67070f30f50a572ac1
Description-en: development files and documentation for libcurl (OpenSSL flavour)
 libcurl is an easy-to-use client-side URL transfer library, supporting DICT,
 FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, POP3, POP3S,
 RTMP, RTSP, SCP, SFTP, SMTP, SMTPS, TELNET and TFTP.
 .
 libcurl supports SSL certificates, HTTP POST, HTTP PUT, FTP uploading, HTTP
 form based upload, proxies, cookies, user+password authentication (Basic,
 Digest, NTLM, Negotiate, Kerberos), file transfer resume, http proxy tunneling
 and more!
 .
 libcurl is free, thread-safe, IPv6 compatible, feature rich, well supported,
 fast, thoroughly documented and is already used by many known, big and
 successful companies and numerous applications.
 .
 This package provides the development files (ie. includes, static library,
 manual pages) that allow to build software which uses libcurl.
 .
 SSL support is provided by OpenSSL.
Description-md5: 9ef3e0d3a9a6f50f79b0deaff858c410
Multi-Arch: same
Homepage: http://curl.haxx.se
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
```

**Comment by job13er** [comment]
Hmmm. That's the same lib that is on our linux build machine. Strange. 

This line looks  troubling:

```
/home/gajo/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25
```

Are you using `node@0.12.x`? `beaker` only works on `0.10.x` currently, as specified in the [`package.json`](https://github.com/cyaninc/beaker/blob/master/package.json#L140)

I'm working on adding support for `iojs` though, then we can use some es6 syntax in our node code :smile:

**Comment by job13er** [comment]
I should probably throw an `engineStrict` in there, so it complains loudly when trying to install it on a different engine. I'm not sure what `engines` does when `engineStrict` isn't set, actually.

**Comment by garrickajo** [comment]
Ok, I've got something to work with. Thank you very much!

Hmm, I can run 10 under 'nodejs', but how to make npm use that with the
install, or can it....? No easy answers on search.

Yesss, es6!

**Comment by job13er** [comment]
@garrickajo use [`nvm`](https://github.com/creationix/nvm) to manage your node versions. Then it's as simple as setting an `.nvmrc` in your project directory where you wanna use `beaker`:

I'll look like this: 
```
0.10
```
and doing an:
```
nvm install
nvm use
```
You'll then be working with `node@0.10.x` and the associated `npm`. To switch to another version, say, 0.12, you can just do `nvm install 0.12` and `nvm use 0.12` I would **highly** recommend using `nvm`, it prevents you from having to use `sudo` to `-g` install stuff, because it stores everything in a `~/.nvm` directory instead of `/usr/lib/` or somewhere else only `root` can write.

**Comment by garrickajo** [comment]
Ahh, nice! Thanks for the intro. I'm definitely going to get into that.

**Comment by garrickajo** [comment]
Just to confirm, the issue I had noted is definitely because of the
version. Now I'm running nvm, installing npm dependecies ran no problems.

**Comment by job13er** [comment]
@garrickajo Glad to hear it :smile:
